apiVersion: apps/v1
kind: Deployment
metadata:
  name: slow-http-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: slow-http-server
  template:
    metadata:
      labels:
        app: slow-http-server
    spec:
      containers:
        - name: slow-http-server
          image: tallongsun/slow-http-server:0.1
---
apiVersion: v1
kind: Service
metadata:
  name: slow-http-server-service
spec:
  type: ClusterIP
  selector:
    app: slow-http-server
  ports:
    - name: http
      port: 80
      targetPort: 80
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: slow-http-server-service-ingress
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`your.example.com`)
      kind: Rule
      services:
        - name: slow-http-server-service
          port: 80

